### ISSUE TITLE
Updated action-wp-org-deploy version

### ISSUE THREAD

**Issue by varunsridharan** [netdesignr/remove-admin-toolbar#2]
Hi,

This project use the GitHub action [varunsridharan/action-wp-org-deploy](https://github.com/varunsridharan/action-wp-org-deploy) on the [master](https://github.com/varunsridharan/action-wp-org-deploy/tree/master) branch.

Due to changes into the branches management, the `master` branch is not longer supported and will be removed in 1 month
 _(EOL: 2020-11-28)_.

The current latest version is `1.3` from the [main](https://github.com/varunsridharan/action-github-workflow-sync/tree/main) branch.

```yaml
uses: varunsridharan/action-wp-org-deploy@1.3
```

OR

```yaml
uses: varunsridharan/action-wp-org-deploy@main
```

**Comment by netdesignr** [comment]
Updated accordingly. Thanks for letting me know @varunsridharan
